choco install googlechrome;
choco install git.install;
choco install intellijidea-community;
choco install postman;
choco install docker-desktop;
choco install teamviewer;
choco install openjdk11;
choco install maven;
choco install opera-gx;