choco uninstall googlechrome;
choco uninstall git.install;
choco uninstall intellijidea-community;
choco uninstall postman;
choco uninstall docker-desktop;
choco uninstall teamviewer;
choco uninstall openjdk11;
choco uninstall maven;
choco uninstall opera-gx;